### [실습] 다양한 방법으로 배열 생성
NumPy를 사용하여 다음과 같은 배열을 생성해 보세요.

1. 크기가 4x3인 모든 값이 0인 배열
2. 크기가 3x3인 모든 값이 1인 배열
3. 0에서 20까지 5씩 증가하는 값으로 구성된 배열
4. 0과 1 사이의 4개의 등간격 값을 가진 배열
5. *크기가 2x2인 정규 분포로 구성된 배열*

In [6]:
import numpy as np
# 1.
zeros_array = np.zeros((4,3), dtype=int)
print(zeros_array)
# 2.
ones_array = np.ones((3,3), dtype=int)
print(ones_array)

# 3.
arr1 = np.arange(0, 21, 5)
print("arr1: ", arr1)

# 4.
arr2 = np.linspace(0, 1, 4)
print("arr2: ", arr2)

# 5.
normal_array = np.random.normal(0, 1, (2,2))
print("정규분포 배열: \n", normal_array)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
arr1:  [ 0  5 10 15 20]
arr2:  [0.         0.33333333 0.66666667 1.        ]
정규분포 배열: 
 [[-0.36393416 -0.69530334]
 [-0.69413786  0.2652797 ]]


### [실습 1] 인덱싱과 슬라이싱
1. 배열 `arr`에서 1번째 열만 추출
2. 배열 `arr`에서 1번째 행, 2번째 열의 값을 출력
3. 배열 `arr`에서 첫 번째 행부터 두 번째 행까지 선택하고, 0번째와 1번째 열만 추출

 arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [10]:
import numpy as np
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
result1 = arr[:,0]
print(result1)

[10 40 70]


In [14]:
result2 = arr[0][1]
print(result2)

20


In [ ]:
result3 = arr[2:3, ]