# [3] Numpy: 연산

### [실습] 데이터를 기반으로 배열 연산 수행


다음과 같은 과일 판매량 데이터가 있습니다. 각 과일의 1분기와 2분기 판매량이 주어졌을 때, NumPy 배열을 사용하여 아래 문제를 해결하세요.

1. 1분기와 2분기의 과일별 총 판매량을 구하세요.
2. 과일별 평균 판매량을 구하세요.

- **데이터**:
    - 1분기 판매량: `[200, 340, 150, 400]` (사과, 배, 오렌지, 바나나)
    - 2분기 판매량: `[220, 300, 180, 420]` (사과, 배, 오렌지, 바나나)

In [11]:
import numpy as np
from numpy import dtype

fruits = np.array(['사과', '배', '오렌지', '바나나'])

q1 = np.array([200, 340, 150, 400])
q2 = np.array([220, 300, 180, 420])

result1 = q1+q2
print(result1)
result2 = np.array([q1, q2])
print(result2.mean(axis=0, dtype=int))

[420 640 330 820]
[210 320 165 410]


### [실습 1] 기본 산술 연산


다음 두 배열을 사용하여 각각의 요소별로 덧셈, 뺄셈, 곱셈, 나눗셈을 수행하세요.


```python
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])
```

In [12]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


### [실습 2] Dot Product


다음 두 배열 간의 내적 연산을 수행하세요.


```python
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
```

In [14]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr1 @ arr2

np.int64(32)

### [실습 3] 브로드캐스팅


아래의 2차원 배열과 1차원 배열을 브로드캐스팅하여 더하세요.


```python
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([10, 20, 30])
```

In [15]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([10, 20, 30])

print(arr2d + arr1d)

[[11 22 33]
 [14 25 36]]


### [실습 4] 비교 연산 및 집계 함수 사용


1. 배열에서 20보다 큰 값을 찾아 출력하세요.
2. 배열의 합계, 최대값, 최소값, 평균을 계산하세요.

```python
arr = np.array([10, 20, 30, 40, 50])
```

In [23]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[arr>20])
print(arr.sum())
print(arr.max())
print(arr.min())
print(arr.mean())

[30 40 50]
150
50
10
30.0
